// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farms.sql

package database

import (
	"context"
	"database/sql"
)

const createFarm = `-- name: CreateFarm :one
INSERT INTO farms (
    user_id,
    name,
    location,
    crop_type,
    size_acres
) VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, location, crop_type, size_acres, created_at, updated_at
`

type CreateFarmParams struct {
	UserID    int64           `json:"user_id"`
	Name      string          `json:"name"`
	Location  string          `json:"location"`
	CropType  string          `json:"crop_type"`
	SizeAcres sql.NullFloat64 `json:"size_acres"`
}

func (q *Queries) CreateFarm(ctx context.Context, arg CreateFarmParams) (Farm, error) {
	row := q.db.QueryRowContext(ctx, createFarm,
		arg.UserID,
		arg.Name,
		arg.Location,
		arg.CropType,
		arg.SizeAcres,
	)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Location,
		&i.CropType,
		&i.SizeAcres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFarm = `-- name: DeleteFarm :exec
DELETE FROM farms
WHERE id = ?
`

func (q *Queries) DeleteFarm(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFarm, id)
	return err
}

const getFarm = `-- name: GetFarm :one
SELECT id, user_id, name, location, crop_type, size_acres, created_at, updated_at
FROM farms
WHERE id = ?
`

func (q *Queries) GetFarm(ctx context.Context, id int64) (Farm, error) {
	row := q.db.QueryRowContext(ctx, getFarm, id)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Location,
		&i.CropType,
		&i.SizeAcres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFarmsByUser = `-- name: ListFarmsByUser :many
SELECT id, user_id, name, location, crop_type, size_acres, created_at, updated_at
FROM farms
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListFarmsByUser(ctx context.Context, userID int64) ([]Farm, error) {
	rows, err := q.db.QueryContext(ctx, listFarmsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Farm
	for rows.Next() {
		var i Farm
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Location,
			&i.CropType,
			&i.SizeAcres,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFarm = `-- name: UpdateFarm :one
UPDATE farms
SET
    name = ?,
    location = ?,
    crop_type = ?,
    size_acres = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND user_id = ?
RETURNING id, user_id, name, location, crop_type, size_acres, created_at, updated_at
`

type UpdateFarmParams struct {
	Name      string          `json:"name"`
	Location  string          `json:"location"`
	CropType  string          `json:"crop_type"`
	SizeAcres sql.NullFloat64 `json:"size_acres"`
	ID        int64           `json:"id"`
	UserID    int64           `json:"user_id"`
}

func (q *Queries) UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Farm, error) {
	row := q.db.QueryRowContext(ctx, updateFarm,
		arg.Name,
		arg.Location,
		arg.CropType,
		arg.SizeAcres,
		arg.ID,
		arg.UserID,
	)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Location,
		&i.CropType,
		&i.SizeAcres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
