// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateFarm(ctx context.Context, arg CreateFarmParams) (Farm, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFarm(ctx context.Context, id int64) error
	GetFarm(ctx context.Context, id int64) (Farm, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListFarmsByUser(ctx context.Context, userID int64) ([]Farm, error)
	UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Farm, error)
}

var _ Querier = (*Queries)(nil)
